### ISSUE TITLE
Dimming not working as expected

### ISSUE THREAD

**Issue by gildebrand** [calle-gunnarsson/NexaCtrl#3] opened 2017-05-05 21:49 UTC
Hi!

Thanks for this great repository for talking with Nexa 😄 
I've run into an issue with dimming receivers. I can turn them on and off, but I can't seem to dim them. Whenever I run the `DeviceDim` method, the Nexa dimmer starts dimming up and down for a while (like when pressing a button on the Nexa remote). It doesn't seem to matter what dim value I pass along, it will always start oscillating the intensity of the lightbulb connected to the receiver.

Any ideas why this is? Am I using the wrong kind of Nexa receiver?

**Comment by calle-gunnarsson** [comment] 2017-05-19 06:35
Hi!

I've actually not used this library for several years and I've don't got any hardware setup, but I can try to help you anyway :) Can you paste the code that creates this issue? :)

**Comment by jjssoftware** [comment] 2017-06-24 14:24
I've experienced the same repeating dim up / dim down cycle with Home Easy HE107G and HE108G switches. Not just using this library either because I can reproduce the same phenomenon when using the "official" HE100 remote control.

In my case this is easy to reproduce - it's a case of simply sending an ON to the switch when it's already ON or sending an OFF to the switch when it's already OFF. Doing this gets the switch into the oscillating dim up / dim down state. 

I put this down to not very good onboard firmware flashed in the switches.

**Comment by calle-gunnarsson** [comment] 2017-07-06 07:00
Well, that's expected behavior as far as I know.

Can I close this issue?

**Comment by jjssoftware** [comment] 2017-07-06 07:11
@calle-gunnarsson I agree you're probably correct, rightly or wrongly this is just how it is and there's nothing that can be done by the sender (this library or similar) to change / prevent this behavior. @gildebrand can make a call on closing this down though because he originally raised it.

**Comment by gildebrand** [comment] 2017-09-13 20:10
Sorry about my late reply. Home automation is fun, but there's way too little time to do it on 😿 

I've tried different dimmers, as well as one dimmer that is suppose to work with absolute dimming (the EYCR-201), and they all behave the same. I guess I should pick up a more advanced remote with absolute dimming capabilities to see what data is being transmitted.

Have any of you tried dimming and got it working?

**Comment by jjssoftware** [comment] 2017-09-13 20:36
Although there is dimming support in this library (and my fork) I've not tried it out. I played with a HE100 remote control for a bit and that did have the ability to dim my home easy switches up and down but even that remote also had the ability to get the switches going into the undesirable dim up / dim down oscillating cycle on occasion. 

My take on this situation is that these home easy 433Mhz devices are not very good for real automation because they're basically fire and forget devices with no state feedback mechanism. 

Personally I've pretty much given up on them and prefer sonoff esp8266 switches running custom firmware supporting MQTT nowadays.

**Comment by calle-gunnarsson** [comment] 2017-09-14 11:25
The original library did only had the support to turn switches on and off, that's why I added absolute dimming. And with dimmers from Nexa I've had it running without any issues. But as @jjssoftware mentioned, 433MHz devices are not ideal for home automation since you don't now the current state of the device.

**Closed** 2017-11-25 10:47 UTC
